apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsservico-deployment
  labels:
    app: microsservico
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microsservico
  template:
    metadata:
      labels:
        app: microsservico
    spec:
      containers:
      - name: microsservico
        image: microsservico:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: postgres
        image: postgres:14-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "microsservico_db"
        ports:
        - containerPort: 5432
      - name: redis
        image: redis:6-alpine
        ports:
        - containerPort: 6379
