apiVersion: v1
kind: Service
metadata:
  name: microsservico-service
  labels:
    app: microsservico
spec:
  selector:
    app: microsservico
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
